-- EconoWay - schema PostgreSQL para novos ambientes.
-- IMPORTANTE: antes de aplicar em um banco Neon existente, exporte o schema atual
-- e compare com este baseline. Nao use este arquivo como migracao destrutiva.

CREATE TABLE IF NOT EXISTS conta (
  id_conta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_conta VARCHAR(20) NOT NULL CHECK (tipo_conta IN ('USUARIO', 'SUPERMERCADO', 'ADMIN')),
  status_conta BOOLEAN NOT NULL DEFAULT TRUE,
  dt_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  senha VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL,
  nome VARCHAR(120) NOT NULL,
  cep VARCHAR(8),
  ultimo_login TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_conta_email_lower ON conta (LOWER(email));

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conta BIGINT NOT NULL UNIQUE REFERENCES conta(id_conta) ON DELETE CASCADE,
  aceite_lgpd BOOLEAN NOT NULL DEFAULT FALSE,
  tipo_veiculo VARCHAR(50),
  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),
  endereco VARCHAR(255),
  saldo_receita NUMERIC(12, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS administrador (
  id_admin BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conta BIGINT NOT NULL UNIQUE REFERENCES conta(id_conta) ON DELETE CASCADE,
  nivel_acesso VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
  area_responsavel VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS supermercado (
  id_supermercado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj VARCHAR(14) NOT NULL UNIQUE CHECK (cnpj ~ '^[0-9]{14}$'),
  nome_fantasia VARCHAR(120) NOT NULL,
  endereco_completo VARCHAR(255) NOT NULL,
  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),
  reputacao_media NUMERIC(3, 2) NOT NULL DEFAULT 0 CHECK (reputacao_media BETWEEN 0 AND 5),
  esta_aberto BOOLEAN NOT NULL DEFAULT TRUE,
  status_cadastro VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_cadastro IN ('PENDENTE', 'APROVADO', 'SUSPENSO')),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS supermercado_responsavel (
  id_supermercado BIGINT NOT NULL REFERENCES supermercado(id_supermercado) ON DELETE CASCADE,
  id_conta BIGINT NOT NULL REFERENCES conta(id_conta) ON DELETE CASCADE,
  papel VARCHAR(30) NOT NULL DEFAULT 'GESTOR',
  status VARCHAR(20) NOT NULL DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'PENDENTE', 'BLOQUEADO')),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_supermercado, id_conta)
);

CREATE TABLE IF NOT EXISTS produto (
  id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_barras VARCHAR(64) NOT NULL UNIQUE,
  nome_produto VARCHAR(160) NOT NULL,
  marca VARCHAR(100),
  categoria VARCHAR(80),
  peso NUMERIC(12, 3),
  unidade_medida VARCHAR(30),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS oferta_supermercado (
  id_supermercado BIGINT NOT NULL REFERENCES supermercado(id_supermercado) ON DELETE CASCADE,
  id_produto BIGINT NOT NULL REFERENCES produto(id_produto) ON DELETE CASCADE,
  preco_atual NUMERIC(12, 2) NOT NULL CHECK (preco_atual > 0),
  preco_fidelidade NUMERIC(12, 2) CHECK (preco_fidelidade IS NULL OR preco_fidelidade > 0),
  fonte VARCHAR(30) NOT NULL DEFAULT 'MANUAL'
    CHECK (fonte IN ('MANUAL', 'IMPORTACAO', 'NFCE', 'API_PARCEIRO')),
  data_atualizacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_supermercado, id_produto)
);

CREATE TABLE IF NOT EXISTS favorito_supermercado (
  id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
  id_supermercado BIGINT NOT NULL REFERENCES supermercado(id_supermercado) ON DELETE CASCADE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_usuario, id_supermercado)
);

CREATE TABLE IF NOT EXISTS carrinho (
  id_carrinho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'ABERTO' CHECK (status IN ('ABERTO', 'COMPARADO', 'ARQUIVADO')),
  data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS item_carrinho (
  id_item_carrinho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_carrinho BIGINT NOT NULL REFERENCES carrinho(id_carrinho) ON DELETE CASCADE,
  id_produto BIGINT NOT NULL REFERENCES produto(id_produto),
  quantidade INTEGER NOT NULL CHECK (quantidade > 0),
  preco_unitario NUMERIC(12, 2),
  UNIQUE (id_carrinho, id_produto)
);

CREATE TABLE IF NOT EXISTS comparacao (
  id_comparacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_carrinho BIGINT NOT NULL REFERENCES carrinho(id_carrinho) ON DELETE CASCADE,
  data_comparacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valor_mercado_escolhido NUMERIC(12, 2),
  nome_supermercado_mais_barato VARCHAR(120),
  lista_precos_concorrentes JSONB,
  valor_media_tres_mercados NUMERIC(12, 2),
  economia_potencial NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estrategia VARCHAR(30) NOT NULL DEFAULT 'MENOR_TOTAL'
    CHECK (estrategia IN ('MENOR_TOTAL', 'FAVORITOS', 'PROXIMOS', 'SELECIONADOS'))
);

CREATE INDEX IF NOT EXISTS idx_usuario_id_conta ON usuario(id_conta);
CREATE INDEX IF NOT EXISTS idx_supermercado_responsavel_conta ON supermercado_responsavel(id_conta);
CREATE INDEX IF NOT EXISTS idx_produto_nome_lower ON produto(LOWER(nome_produto));
CREATE INDEX IF NOT EXISTS idx_produto_categoria ON produto(categoria);
CREATE INDEX IF NOT EXISTS idx_oferta_produto_preco ON oferta_supermercado(id_produto, preco_atual);
CREATE INDEX IF NOT EXISTS idx_oferta_atualizacao ON oferta_supermercado(data_atualizacao DESC);
CREATE INDEX IF NOT EXISTS idx_carrinho_usuario_status ON carrinho(id_usuario, status);
CREATE INDEX IF NOT EXISTS idx_comparacao_carrinho_data ON comparacao(id_carrinho, data_comparacao DESC);
CREATE INDEX IF NOT EXISTS idx_supermercado_geo ON supermercado(latitude, longitude);
