-- Funcionalidades de contribuicao de dados, EconoCoins, importacao e auditoria.

CREATE TABLE IF NOT EXISTS nota_fiscal (
  id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
  id_supermercado BIGINT NOT NULL REFERENCES supermercado(id_supermercado),
  chave_acesso VARCHAR(44),
  url_qrcode TEXT NOT NULL,
  hash_documento VARCHAR(64) NOT NULL,
  data_emissao TIMESTAMPTZ,
  processada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status VARCHAR(20) NOT NULL DEFAULT 'VALIDA' CHECK (status IN ('VALIDA', 'DUPLICADA', 'REJEITADA')),
  UNIQUE (hash_documento)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_nota_chave_acesso
  ON nota_fiscal(chave_acesso)
  WHERE chave_acesso IS NOT NULL;

CREATE TABLE IF NOT EXISTS nota_item (
  id_nota_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_nota BIGINT NOT NULL REFERENCES nota_fiscal(id_nota) ON DELETE CASCADE,
  id_produto BIGINT REFERENCES produto(id_produto),
  codigo_barras VARCHAR(64),
  nome_produto VARCHAR(160) NOT NULL,
  quantidade NUMERIC(12, 3) NOT NULL DEFAULT 1 CHECK (quantidade > 0),
  preco_unitario NUMERIC(12, 2) NOT NULL CHECK (preco_unitario > 0)
);

CREATE TABLE IF NOT EXISTS econocoin_evento (
  id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
  tipo VARCHAR(40) NOT NULL CHECK (tipo IN (
    'NFCE_VALIDADA',
    'BONUS_MARCO',
    'AJUSTE_ADMINISTRATIVO',
    'RESGATE'
  )),
  pontos INTEGER NOT NULL CHECK (pontos <> 0),
  referencia_tipo VARCHAR(40),
  referencia_id BIGINT,
  politica_versao VARCHAR(20) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id_usuario, tipo, referencia_tipo, referencia_id)
);

CREATE INDEX IF NOT EXISTS idx_econocoin_usuario_data
  ON econocoin_evento(id_usuario, criado_em DESC);

CREATE TABLE IF NOT EXISTS importacao_preco (
  id_importacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_supermercado BIGINT NOT NULL REFERENCES supermercado(id_supermercado),
  id_conta_responsavel BIGINT NOT NULL REFERENCES conta(id_conta),
  formato VARCHAR(10) NOT NULL CHECK (formato IN ('CSV', 'JSON')),
  nome_arquivo VARCHAR(255) NOT NULL,
  checksum_sha256 VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'VALIDANDO'
    CHECK (status IN ('VALIDANDO', 'PENDENTE_CONFIRMACAO', 'PROCESSANDO', 'CONCLUIDA', 'FALHOU')),
  total_registros INTEGER NOT NULL DEFAULT 0,
  registros_validos INTEGER NOT NULL DEFAULT 0,
  registros_invalidos INTEGER NOT NULL DEFAULT 0,
  criada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  concluida_em TIMESTAMPTZ,
  UNIQUE (id_supermercado, checksum_sha256)
);

CREATE TABLE IF NOT EXISTS importacao_preco_erro (
  id_erro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_importacao BIGINT NOT NULL REFERENCES importacao_preco(id_importacao) ON DELETE CASCADE,
  linha INTEGER,
  codigo VARCHAR(50) NOT NULL,
  mensagem TEXT NOT NULL,
  registro JSONB
);

CREATE TABLE IF NOT EXISTS auditoria (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_conta BIGINT REFERENCES conta(id_conta) ON DELETE SET NULL,
  acao VARCHAR(100) NOT NULL,
  entidade VARCHAR(80) NOT NULL,
  entidade_id VARCHAR(100),
  dados JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auditoria_entidade_data
  ON auditoria(entidade, criado_em DESC);
